// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.CreateNotificationForAllUsersExceptOne_Creates_Notifications_For_All_Users_Except_one~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2006:Consider using Assert.That(actual, Is.Not.EqualTo(expected)) instead of Assert.AreNotEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.CreateNotificationForAllUsersExceptOne_Creates_Notifications_For_All_Users_Except_one~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.GetNotification_Returns_Notification_For_Given_Id~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.CreateNotificationForAllUsers_Creates_Notification_For_All_Users~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.GetNotificationsForUser_Returns_Notifications_For_User~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.CreateNotificationForSpecificUser_Creates_Notification_For_Specific_User~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.ProductServiceTests.EditProduct_Updates_Product_Details~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.GetTop20ProductRelatedNotification_Returns_Top_20_Product_Related_Notifications~System.Threading.Tasks.Task")]
