// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.CreateNotificationForAllUsersExceptOne_Creates_Notifications_For_All_Users_Except_one~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2006:Consider using Assert.That(actual, Is.Not.EqualTo(expected)) instead of Assert.AreNotEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.CreateNotificationForAllUsersExceptOne_Creates_Notifications_For_All_Users_Except_one~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.GetNotification_Returns_Notification_For_Given_Id~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.CreateNotificationForAllUsers_Creates_Notification_For_All_Users~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.GetNotificationsForUser_Returns_Notifications_For_User~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.CreateNotificationForSpecificUser_Creates_Notification_For_Specific_User~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.ProductServiceTests.EditProduct_Updates_Product_Details~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.NotificationServiceTests.GetTop20ProductRelatedNotification_Returns_Top_20_Product_Related_Notifications~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.HomeTelemetryTests.CreateNotificationIfDataIsAbnormal_SendsNotification~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.GetAllRecipes_ReturnsRecipesPaginationViewModel_WithNonStartedRecipes~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.AddRecipe_AddsRecipeAndImage_WhenRecipeImageIsNotNull~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.AddStep_AddsNormalStep_WhenRecipeExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.AddStep_AddsNormalStepWithProducts_WhenRecipeExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.GetAllRecipes_ReturnsRecipesPaginationViewModel_WithStartedRecipes~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.GetLastStepDetails_GetsLastStep_WhenItExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.GetProductsForRecipe_ReturnsProductViewModels_WhenRecipeExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.GetRecipe_ReturnsRecipeDetailsViewModel_WhenRecipeExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.MoveNextUserRecipeStep_AddsUserStep_WhenNoUserStepExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.MoveNextUserRecipeStep_IncrementsStep_WhenUserStepExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.ChangeStepPosition_ChangesStepPosition_WhenOldAndNewStepNumbersAreValid~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.DeleteRecipe_DeletesRecipeAndAssociatedEntities_WhenRecipeExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.DeleteStep_RemovesStepAndUpdatesStepNumbers_WhenStepExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.EditRecipe_UpdatesRecipe_WhenRecipeExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.EditStep_UpdatesStepAndAssociatedProducts_WhenStepExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.GetRecipeFormViewModel_ReturnsRecipeFormViewModel_WhenRecipeExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.GetStep_ReturnsStepFormViewModel_WhenStepExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.GetUserStep_ReturnsStepDetailsViewModel_WhenUserStepExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.RecipeServiceTests.UpdateProductQuantities_DecreasesProductQuantities_WhenProductsExistAndQuantitiesAreValid~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Assertion", "NUnit2005:Consider using Assert.That(actual, Is.EqualTo(expected)) instead of Assert.AreEqual(expected, actual)", Justification = "<Pending>", Scope = "member", Target = "~M:UnitTests.ShoppingListServiceTests.GetProductsByCategory_ShouldReturnCorrectProducts~System.Threading.Tasks.Task")]
